/**
 * BharatVow module registry — single source of truth for dashboard tools and sub-pages.
 *
 * Sync target: mobile app `MY_SERVICES` in DashboardScreen.js (D:\AirVow\private).
 * Phase 1 keeps current website values unchanged; Phase 2 updates this file only.
 *
 * @see MODULES_ARCHITECTURE.md
 */

/** @typedef {'money' | 'home' | 'family' | 'vehicle' | 'grocery' | 'travel' | 'daily-life'} LifeAreaSlug */

/**
 * @typedef {Object} ModuleConfig
 * @property {string | null} key App MY_SERVICES key (null for website-only sub-pages)
 * @property {string} slug Website route segment
 * @property {string} displayName Public module name
 * @property {string} shortName Compact label (hero chips, lists)
 * @property {string} iconKey Key into moduleIcons.js
 * @property {number | null} order Dashboard tile order (1-based); null if not on dashboard
 * @property {boolean} onDashboard Listed on main dashboard grid
 * @property {boolean} alwaysFree Free without subscription
 * @property {boolean} enabled Included in website module registry
 * @property {string} screenshotId Canonical screenshot manifest ID
 * @property {string} dashboardLabel Tile label (matches displayName today)
 * @property {string} dashboardSubLabel1 First dashboard sublabel line
 * @property {string} dashboardSubLabel2 Second dashboard sublabel line
 * @property {string | null} category Deprecated grouping id (MODULE_GROUPS); null if ungrouped
 * @property {LifeAreaSlug} lifeArea Life area slug for bento / grouping
 * @property {string} route Canonical tool path
 * @property {string} seoKey Stable SEO registry key (usually slug)
 * @property {string} tagline One-line marketing tagline
 * @property {string} purpose Tool purpose sentence
 * @property {string} problem Relatable problem statement
 * @property {string | null} [parentSlug] Parent module slug for sub-pages
 * @property {boolean} [isSubPage] Website-only sub-page (not on dashboard)
 * @property {string | null} [parentKey] Parent MY_SERVICES key for sub-pages
 */

const DIGITAL_LIFE_BASE = '/digital-life';

/**
 * All BharatVow modules — dashboard tools in `order`, then sub-pages.
 * @type {ModuleConfig[]}
 */
export const MODULE_REGISTRY = [
  {
    key: 'KHATA',
    slug: 'smart-khata',
    displayName: 'Smart Khata',
    shortName: 'Smart Khata',
    iconKey: 'HandCoins',
    order: 1,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'smart-khata',
    dashboardLabel: 'Smart Khata',
    dashboardSubLabel1: 'Track lend-and-borrow',
    dashboardSubLabel2: 'and borrowing',
    category: 'budget-daily',
    lifeArea: 'money',
    route: `${DIGITAL_LIFE_BASE}/smart-khata`,
    seoKey: 'smart-khata',
    tagline: 'Lend-and-borrow records with a clear running balance',
    purpose: 'Track lend-and-borrow entries with a clear running balance per person.',
    problem: 'Kitna udhaar baaki hai — yaad hi nahi.',
  },
  {
    key: 'GOODBUDGET',
    slug: 'budget-pocket',
    displayName: 'Budget Pocket',
    shortName: 'Budget Pocket',
    iconKey: 'PieChart',
    order: 2,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'budget-pocket',
    dashboardLabel: 'Budget Pocket',
    dashboardSubLabel1: 'Plan and control',
    dashboardSubLabel2: 'budget',
    category: 'budget-daily',
    lifeArea: 'money',
    route: `${DIGITAL_LIFE_BASE}/budget-pocket`,
    seoKey: 'budget-pocket',
    tagline: 'Household budget limits by category before the month runs out',
    purpose: 'Plan and control household budget by category before the month slips away.',
    problem: 'Mahine ka budget pehle hi khatam ho jata hai.',
  },
  {
    key: 'EXPENSES',
    slug: 'expenses-diary',
    displayName: 'Expenses Diary',
    shortName: 'Expenses Diary',
    iconKey: 'NotebookPen',
    order: 3,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'expenses-diary',
    dashboardLabel: 'Expenses Diary',
    dashboardSubLabel1: 'Manage daily',
    dashboardSubLabel2: 'expense records',
    category: 'budget-daily',
    lifeArea: 'money',
    route: `${DIGITAL_LIFE_BASE}/expenses-diary`,
    seoKey: 'expenses-diary',
    tagline: 'Daily expense diary — see where household spending actually went',
    purpose: 'Manage daily expense records so you know where spending actually went.',
    problem: 'Cash kharcha dikhta hi nahi.',
  },
  {
    key: 'EVENTS',
    slug: 'event-book',
    displayName: 'Event Book',
    shortName: 'Event Book',
    iconKey: 'CalendarCheck',
    order: 4,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'event-book',
    dashboardLabel: 'Event Book',
    dashboardSubLabel1: 'Plan and',
    dashboardSubLabel2: 'manage events',
    category: 'home-celebrations',
    lifeArea: 'family',
    route: `${DIGITAL_LIFE_BASE}/event-book`,
    seoKey: 'event-book',
    tagline: 'Wedding guests, gifts, and costs in one register',
    purpose: 'Plan and manage events, guests, gifts, and costs in one register.',
    problem: 'Shaadi ki list teen WhatsApp groups me hai.',
  },
  {
    key: 'TRIPS',
    slug: 'trip-ledger',
    displayName: 'Trip Ledger',
    shortName: 'Trip Ledger',
    iconKey: 'Luggage',
    order: 5,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'trip-ledger',
    dashboardLabel: 'Trip Ledger',
    dashboardSubLabel1: 'Split group',
    dashboardSubLabel2: 'trip expenses',
    category: 'travel-vehicles',
    lifeArea: 'travel',
    route: `${DIGITAL_LIFE_BASE}/trip-ledger`,
    seoKey: 'trip-ledger',
    tagline: 'Shared trip costs recorded fairly — settled in minutes',
    purpose: 'Split group trip expense records fairly and review balance summaries quickly.',
    problem: 'Trip khatam — kaun kitna dega?',
  },
  {
    key: 'VEHICLE',
    slug: 'vehicle-vault',
    displayName: 'Vehicle Vault',
    shortName: 'Vehicle Vault',
    iconKey: 'Car',
    order: 6,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'vehicle-vault',
    dashboardLabel: 'Vehicle Vault',
    dashboardSubLabel1: 'Track all vehicle',
    dashboardSubLabel2: 'expenses',
    category: 'travel-vehicles',
    lifeArea: 'vehicle',
    route: `${DIGITAL_LIFE_BASE}/vehicle-vault`,
    seoKey: 'vehicle-vault',
    tagline: 'RC, insurance, and service history on your phone',
    purpose: 'Track all vehicle documents, renewals, fuel, and service records.',
    problem: 'RC ghar pe tha jab zarurat padi.',
  },
  {
    key: 'HOME_VAULT',
    slug: 'home-vault',
    displayName: 'Home Vault',
    shortName: 'Home Vault',
    iconKey: 'Home',
    order: 7,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'home-vault',
    dashboardLabel: 'Home Vault',
    dashboardSubLabel1: 'Manage home assets',
    dashboardSubLabel2: 'bills & services',
    category: 'home-celebrations',
    lifeArea: 'home',
    route: `${DIGITAL_LIFE_BASE}/home-vault`,
    seoKey: 'home-vault',
    tagline: 'Bills, maintenance, and household knowledge in one place',
    purpose: 'Manage home assets, bills, due services, and household knowledge in one vault.',
    problem: 'Ghar sambhalna — yaad rakhna impossible lagta hai.',
  },
  {
    key: 'BIRTHDAY',
    slug: 'days-reminder',
    displayName: 'Days Reminder',
    shortName: 'Days Reminder',
    iconKey: 'BellRing',
    order: 8,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'days-reminder',
    dashboardLabel: 'Days Reminder',
    dashboardSubLabel1: 'Remember important',
    dashboardSubLabel2: 'special days',
    category: 'home-celebrations',
    lifeArea: 'family',
    route: `${DIGITAL_LIFE_BASE}/days-reminder`,
    seoKey: 'days-reminder',
    tagline: "Today's birthdays and anniversaries every morning",
    purpose: 'Remember important birthdays, anniversaries, and custom dates each morning.',
    problem: 'Birthday wish karna bhool gaya — phir awkward.',
  },
  {
    key: 'LISTONIC',
    slug: 'grocery-bag',
    displayName: 'Grocery Bag',
    shortName: 'Grocery Bag',
    iconKey: 'ShoppingBag',
    order: 9,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'grocery-bag',
    dashboardLabel: 'Grocery Bag',
    dashboardSubLabel1: 'Create smart',
    dashboardSubLabel2: 'grocery lists',
    category: 'daily-life',
    lifeArea: 'grocery',
    route: `${DIGITAL_LIFE_BASE}/grocery-bag`,
    seoKey: 'grocery-bag',
    tagline: 'Market list on your phone — check off as you shop',
    purpose: 'Create smart grocery lists and check items off at the market.',
    problem: 'List ghar pe reh gayi.',
  },
  {
    key: 'LINK_VAULT',
    slug: 'link-vault',
    displayName: 'Link Vault',
    shortName: 'Link Vault',
    iconKey: 'BookOpen',
    order: 10,
    onDashboard: true,
    alwaysFree: true,
    enabled: true,
    screenshotId: 'link-vault',
    dashboardLabel: 'Link Vault',
    dashboardSubLabel1: 'Save and organize',
    dashboardSubLabel2: 'important links',
    category: 'daily-life',
    lifeArea: 'daily-life',
    route: `${DIGITAL_LIFE_BASE}/link-vault`,
    seoKey: 'link-vault',
    tagline: 'Save links before WhatsApp scrolls them away',
    purpose: 'Save and organize important links in collections — free without a subscription.',
    problem: 'Woh link WhatsApp me kho gayi.',
  },
  {
    key: 'STATUS_SAVER',
    slug: 'status-viewer',
    displayName: 'Status Viewer',
    shortName: 'Status Viewer',
    iconKey: 'ScanLine',
    order: 11,
    onDashboard: true,
    alwaysFree: true,
    enabled: true,
    screenshotId: 'status-viewer',
    dashboardLabel: 'Status Viewer',
    dashboardSubLabel1: 'View status',
    dashboardSubLabel2: 'media on device',
    category: 'daily-life',
    lifeArea: 'daily-life',
    route: `${DIGITAL_LIFE_BASE}/status-viewer`,
    seoKey: 'status-viewer',
    tagline: 'View, save, and share status media already on your device',
    purpose:
      'Conveniently view, save, and share status media that is already available on your device.',
    problem: 'Status clips disappear before you can save or share them.',
  },
  {
    key: 'placeScreen',
    slug: 'place-store',
    displayName: 'Place Store',
    shortName: 'Place Store',
    iconKey: 'MapPinCheck',
    order: 12,
    onDashboard: true,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'place-store',
    dashboardLabel: 'Place Store',
    dashboardSubLabel1: 'Save places you',
    dashboardSubLabel2: 'frequently visit',
    category: 'travel-vehicles',
    lifeArea: 'travel',
    route: `${DIGITAL_LIFE_BASE}/place-store`,
    seoKey: 'place-store',
    tagline: 'Save places you visit often with notes',
    purpose: 'Save places you frequently visit with notes for your next trip.',
    problem: 'Woh dhaba next trip pe yaad nahi aaya.',
  },
  {
    key: null,
    slug: 'home-assets',
    displayName: 'Home Assets',
    shortName: 'Home Assets',
    iconKey: 'Home',
    order: null,
    onDashboard: false,
    alwaysFree: false,
    enabled: true,
    screenshotId: 'home-vault',
    dashboardLabel: 'Home Assets',
    dashboardSubLabel1: '',
    dashboardSubLabel2: '',
    category: 'home-celebrations',
    lifeArea: 'home',
    route: `${DIGITAL_LIFE_BASE}/home-assets`,
    seoKey: 'home-assets',
    tagline: 'Appliance and furniture records with warranty dates',
    purpose: 'Register appliances and furniture with warranty dates — part of Home Vault.',
    problem: 'Warranty kab khatam hogi — pata hi nahi.',
    parentSlug: 'home-vault',
    parentKey: 'HOME_VAULT',
    isSubPage: true,
  },
];

/** Mobile source reference — update when syncing with app */
export const MODULE_SOURCE = {
  appFile: 'src/screens/Dashboard/DashboardScreen.js',
  appExport: 'MY_SERVICES',
  websiteHubRoute: DIGITAL_LIFE_BASE,
  websiteToolRoutePattern: `${DIGITAL_LIFE_BASE}/:slug`,
};
